feat hardis:org:community:update Add a command to activate or deactivate communities
hardisgroupcom/sfdx-hardis pull request #850
Opened 2024-10-24 08:31 UTC by tprouvot

Hi @nvuillam,

We had the need on one of our project and I though that could be helpful for the community.
Let me know if the PR requires updates and adjustments.

Thanks !

2024-10-24 08:34 UTC, tprouvot commented
I figured out that I was missing the doc, I'll add it

2024-10-24 09:09 UTC, nvuillam requested changes
We're almost goog, please check comments :)

2024-10-24 09:09 UTC, nvuillam commented on src/commands/hardis/org/community/update.ts
> +      const bulkUpdateRes = await bulkUpdate('Network', 'update', networkUpdates, conn);
@tprouvot are you sure you need to use the Bulk API for a single update ? ^^

Otherwise you can use jsforce conn.update

```
// Single record update
const ret = await conn.sobject("Account").update({
  Id: '0010500000fxbcuAAA',
  Name : 'Updated Account #1'
})

if (ret.success) {
  console.log(`Updated Successfully : ${ret.id}`);
}
```

2024-10-24 09:09 UTC, nvuillam commented on src/commands/hardis/org/community/update.ts
> +      return {
freezeSuccess, freezeErrors, are you sure ? :)

2024-10-24 09:10 UTC, nvuillam commented
> I figured out that I was missing the doc, I'll add it

the doc is automatically generated, don't worry , you input field description , that's large enough :)

2024-10-24 09:38 UTC, tprouvot commented on src/commands/hardis/org/community/update.ts
> +      const bulkUpdateRes = await bulkUpdate('Network', 'update', networkUpdates, conn);
We can have more than one community to udpate that's a list

2024-10-24 09:40 UTC, tprouvot commented on src/commands/hardis/org/community/update.ts
> +      return {
Now you know which command I used to create this one 😄

2024-10-24 09:51 UTC, tprouvot commented
Found a bug, let me fix it

2024-10-24 10:05 UTC, tprouvot reviewed
Remove previous comments

2024-10-24 10:05 UTC, tprouvot commented on src/commands/hardis/org/community/update.ts
> +    // Select networks that we want to update
```suggestion
```

2024-10-24 10:05 UTC, tprouvot commented on src/commands/hardis/org/community/update.ts
> +      // Use includenetworks argument
```suggestion
```

2024-10-24 14:45 UTC, nvuillam commented on src/commands/hardis/org/community/update.ts
> +      const bulkUpdateRes = await bulkUpdate('Network', 'update', networkUpdates, conn);
@tprouvot conn.update can take a list up to 200 (REST API behind) :)

2024-11-02 00:14 UTC, nvuillam approved these changes
Great, thank u very much for the PR :)

2024-11-02 00:14 UTC, merged